version: "3.3"

services: 
  
  db: 
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - custom  
    environment:
      POSTGRES_DB: "Person_Database"
      POSTGRES_USER: "foo"
      POSTGRES_PASSWORD: "bar123" 
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - db-data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "juan@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "secretostr123"
      PGADMIN_LISTEN_PORT: "80"
    ports:
      - "8080:80"
    networks:
      - custom 
    depends_on: 
      - "db"

  python:
    build: 
      context: ./Container_3/
    restart: on-failure:20
    container_name: data_extractor
    networks:
      - custom  
    depends_on: 
      - "pgadmin"
    env_file:
      - ./Container_3/env.list
volumes:
  db-data:
  pgadmin-data:

networks:
  custom:
    driver: bridge
